/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
	theme: {
		extend: {
			colors: {
				blueGreen: {
					50: "#1A2E25",
					100: "#1A2E25",
					200: "#1A2E25",
					300: "#1A2E25",
					400: "#1A2E25",
					500: "#1A2E25",
					600: "#1A2E25",
					700: "#1A2E25",
					800: "#1A2E25",
					900: "#1A2E25",
				},
			},
			typography: ({ theme }) => ({
				blueGreen: {
					css: {
						"--tw-prose-body": theme("colors.blueGreen[500]"),
						"--tw-prose-headings": theme("colors.blueGreen[500]"),
						"--tw-prose-lead": theme("colors.blueGreen[500]"),
						"--tw-prose-links": theme("colors.blueGreen[500]"),
						"--tw-prose-bold": theme("colors.blueGreen[500]"),
						"--tw-prose-counters": theme("colors.blueGreen[500]"),
						"--tw-prose-bullets": theme("colors.blueGreen[500]"),
						"--tw-prose-hr": theme("colors.blueGreen[500]"),
						"--tw-prose-quotes": theme("colors.blueGreen[500]"),
						"--tw-prose-quote-borders": theme("colors.blueGreen[500]"),
						"--tw-prose-captions": theme("colors.blueGreen[500]"),
						"--tw-prose-code": theme("colors.blueGreen[500]"),
						"--tw-prose-pre-code": theme("colors.blueGreen[500]"),
						"--tw-prose-pre-bg": theme("colors.blueGreen[500]"),
						"--tw-prose-th-borders": theme("colors.blueGreen[500]"),
						"--tw-prose-td-borders": theme("colors.blueGreen[500]"),
						"--tw-prose-invert-body": theme("colors.blueGreen[500]"),
						"--tw-prose-invert-headings": theme("colors.white"),
						"--tw-prose-invert-lead": theme("colors.blueGreen[500]"),
						"--tw-prose-invert-links": theme("colors.white"),
						"--tw-prose-invert-bold": theme("colors.white"),
						"--tw-prose-invert-counters": theme("colors.blueGreen[500]"),
						"--tw-prose-invert-bullets": theme("colors.blueGreen[500]"),
						"--tw-prose-invert-hr": theme("colors.blueGreen[500]"),
						"--tw-prose-invert-quotes": theme("colors.blueGreen[500]"),
						"--tw-prose-invert-quote-borders": theme("colors.blueGreen[500]"),
						"--tw-prose-invert-captions": theme("colors.blueGreen[500]"),
						"--tw-prose-invert-code": theme("colors.white"),
						"--tw-prose-invert-pre-code": theme("colors.blueGreen[500]"),
						"--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
						"--tw-prose-invert-th-borders": theme("colors.blueGreen[500]"),
						"--tw-prose-invert-td-borders": theme("colors.blueGreen[500]"),
					},
				},
			}),
		},
	},
	plugins: [require("@tailwindcss/typography"), require("@tailwindcss/forms")],
};
