const config = {
	theme: {
		extend: {
			typography: ({ theme }) => ({
				"blue-green": {
					css: {
						"--tw-prose-body": "var(--color-blue-green)",
						"--tw-prose-headings": "var(--color-blue-green)",
						"--tw-prose-lead": "var(--color-blue-green)",
						"--tw-prose-links": "var(--color-blue-green)",
						"--tw-prose-bold": "var(--color-blue-green)",
						"--tw-prose-counters": "var(--color-blue-green)",
						"--tw-prose-bullets": "var(--color-blue-green)",
						"--tw-prose-hr": "var(--color-blue-green)",
						"--tw-prose-quotes": "var(--color-blue-green)",
						"--tw-prose-quote-borders": "var(--color-blue-green)",
						"--tw-prose-captions": "var(--color-blue-green)",
						"--tw-prose-code": "var(--color-blue-green)",
						"--tw-prose-pre-code": "var(--color-blue-green)",
						"--tw-prose-pre-bg": "var(--color-blue-green)",
						"--tw-prose-th-borders": "var(--color-blue-green)",
						"--tw-prose-td-borders": "var(--color-blue-green)",
						"--tw-prose-invert-body": theme("colors.white"),
						"--tw-prose-invert-headings": theme("colors.white"),
						"--tw-prose-invert-lead": theme("colors.white"),
						"--tw-prose-invert-links": theme("colors.white"),
						"--tw-prose-invert-bold": theme("colors.white"),
						"--tw-prose-invert-counters": theme("colors.white"),
						"--tw-prose-invert-bullets": theme("colors.white"),
						"--tw-prose-invert-hr": theme("colors.white"),
						"--tw-prose-invert-quotes": theme("colors.white"),
						"--tw-prose-invert-quote-borders": theme("colors.white"),
						"--tw-prose-invert-captions": theme("colors.white"),
						"--tw-prose-invert-code": theme("colors.white"),
						"--tw-prose-invert-pre-code": theme("colors.white"),
						"--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
						"--tw-prose-invert-th-borders": theme("colors.white"),
						"--tw-prose-invert-td-borders": theme("colors.white"),
					},
				},
			}),
		},
	},
};
export default config;
