import "./globals.css";
import Header from "@/app/components/Header/Header";
import Footer from "@/app/components/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex justify-center">
      <div className="max-w-[1400px] mx-1">
        <Header />
        <main>{children}</main>
        <Footer />
      </div>
      </body>
    </html>
  );
}
